# Generated by Django 5.0.3 on 2024-04-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='computersoftware',
            unique_together={('serialnumber', 'name')},
        ),
    ]
