# Generated by Django 5.0.3 on 2024-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_alter_computersoftware_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employeeid',
            new_name='employeid',
        ),
    ]
