# Generated by Django 5.0.3 on 2024-04-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_alter_monitors_inventory_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='second_model_harddrives',
            field=models.ForeignKey(blank=True, db_column='Second_Model_HardDrives', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers_second_model_harddrives_set', to='proj.harddrives'),
        ),
    ]
