# Generated by Django 5.0.3 on 2024-04-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_rename_employeeid_employees_employeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employeid',
            new_name='employeeid',
        ),
    ]
