# Generated by Django 5.0.3 on 2024-04-19 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_rename_employeid_employees_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, related_name='computers_set', to='proj.employees'),
        ),
        migrations.AlterField(
            model_name='monitors',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, related_name='monitors_set', to='proj.employees'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='employeeid',
            field=models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, related_name='printers_set', to='proj.employees'),
        ),
    ]
