version: "3"

services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - web
      - db
    ports:
      -"8000:8000"


  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      -"80:80"
    volumes:
      - ./static/:/static

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:82
    restart: always
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8081:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password