version: "3"

services:


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    restart: always
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password --pid-file=/var/run/mysqld/mysqld.pid
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password

  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - NAME=django_db
      - HOST=db
      - PASSWORD=django_password
      - USER=django_user
      - PORT=3306


  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      - "80:80"
    volumes:
      - ./static/:/static